name: cmip6-downscaling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - xesmf=0.6.2
  - esmf=8.2.0
  - esmpy=8.2.0
  - pytest
  - pytest-cov
  - pip
  - pip:
      # relative to this file. Needs to be editable to be accepted.
      - -e ../
