name: carbonplan
channels:
  - conda-forge
dependencies:
  - adlfs
  - dask
  - dask-kubernetes
  - fsspec
  - google-cloud-storage
  - gcsfs
  - gstools
  - intake
  - intake-esm
  - intake-xarray
  - prefect
  - pytest
  - pytest-sugar
  - pytest-cov
  - rechunker
  - regionmask
  - scikit-downscale
  - scikit-learn
  - tenacity
  - xarray
  - xesmf
  - xpersist
  - xclim
  - zarr
  - pip
  - pip:
      - git+https://github.com/pangeo-data/scikit-downscale@84cd5f45de4aa61445ca74b85505b035f84fbb80
