name: cmip6-downscaling-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - ipython
  - setuptools
  - sphinx
  - numpydoc
  # this project's dependencies
  - adlfs
  - dask
  - dask-kubernetes
  - donfig
  - fsspec
  - gcsfs
  - intake-esm
  - intake-xarray
  - numpy
  - pandas
  - prefect
  - regionmask
  - scikit-downscale
  - scikit-learn
  - scipy
  - xclim
  - xpersist
  - zarr
  - pip:
      - -e ..
