name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          activate-environment: carbonplan
          channels: conda-forge
          channel-priority: true
          environment-file: envs/python-notebook/environment.yml
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          python -m pip install git+https://github.com/pangeo-data/scikit-downscale@84cd5f45de4aa61445ca74b85505b035f84fbb80
          python -m pip list
      - name: Running Tests
        shell: bash -l {0}
        run: |
          python -m pytest --verbose
