name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly "At 00:00"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install prek
      - run: prek run --all-files

  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.5
        with:
          pixi-version: v0.47.0
          environments: dev
          cache: true

      - name: Run tests
        run: pixi run -e dev pytest tests
