name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly “At 00:00”

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# Note: This CI used to run off of the image:
# carbonplan/cmip6-downscaling-single-user:2022.06.19

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10'] #TODO: add 3.11 once sparse/numba support it
    timeout-minutes: 20
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1.8.0
        with:
          environment-name: cmip6-downscaling
          condarc: |
            channels:
              - conda-forge
              - nodefaults
          cache-downloads: false
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install -e .[dev]
      - name: Conda list information
        run: |
          conda env list
          conda list
      - name: Run tests
        run: |
          python -m pytest tests
