name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: carbonplan/cmip6-downscaling-prefect:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install
        run: |
          python -m pip install --no-deps -e .
          python -m pip list
      - name: Running Tests
        run: |
          python -m pytest --verbose
