name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: carbonplan/cmip6-downscaling-single-user:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          git config --global --add safe.directory /__w/cmip6-downscaling/cmip6-downscaling
          python -m pip install -e .
          python -m pip list
      - name: Running Tests
        run: |
          python -m pytest --verbose
