name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
      - uses: pre-commit/action@v2.0.3

  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: |
          python -m pip install -r dev-requirements.txt
          python -m pip install --no-deps -e .
          python -m pip list
      - name: Running Tests
        run: |
          python -m pytest --verbose
